# Generated by Django 4.0.1 on 2022-10-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
        migrations.AddField(
            model_name='company',
            name='workers',
            field=models.ManyToManyField(to='api.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Deliver'), (4, 'Operator'), (5, 'Customer')], default=5),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('img1', models.ImageField(upload_to='products/img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='products/img')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='products/img')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='products/img')),
                ('sale', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='api.Product'),
        ),
    ]
