# Generated by Django 4.1 on 2022-11-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Deliver'), (4, 'Operator'), (5, 'Customer'), (6, 'User')], default=5),
        ),
    ]
