# Generated by Django 4.1 on 2022-11-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0003_tokenproxy'),
        ('api', '0009_alter_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='My_User',
        ),
    ]
