# Generated by Django 4.1 on 2022-11-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_user_my_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_user',
            name='last_login',
        ),
    ]
