# Generated by Django 4.1 on 2022-11-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_my_user_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_User',
            new_name='User',
        ),
    ]
